baseurl: "/engine"

collections:
  workspaces:
    output: true
    permalink: /:collection/:name/
    defaults:
      -
        scope:
          path: ""
        values:
          layout: "default"

  docs:
    output: true
    permalink: /:collection/:name/
    defaults:
      -
        scope:
          path: ""
        values:
          layout: "docs"

include:
  - "script.js"
  - "favicon.ico"

exclude:
  - tests
  - vendor/
  - verify_loading_screen.py
  - verify_background.py
  - verification/
  - jekyll.log
