baseurl: "/engine"

collections:
  workspaces:
    output: true
    permalink: /:collection/:name/
    defaults:
      -
        scope:
          path: ""
        values:
          layout: "default"

  docs:
    output: true
    permalink: /:collection/:name/
    defaults:
      -
        scope:
          path: ""
        values:
          layout: "docs"

exclude:
  - tests
  - vendor/
