name: Junie
run-name: Junie run ${{ inputs.run_id }}

permissions:
    pull-requests: write

on:
    workflow_dispatch:
        inputs:
            run_id:
                description: "id of workflow process"
                required: true
            workflow_params:
                description: "stringified params"
                required: true

jobs:
    call-workflow-passing-data:
        uses: jetbrains-junie/junie-workflows/.github/workflows/ej-issue.yml@main
        with:
            workflow_params: ${{ inputs.workflow_params }}
            runs-on: "ubuntu-latest"  # Optional: Specify which runner to use
        secrets:
            JUNIE_SECRETS_JSON: ${{ secrets.JUNIE_SECRETS_JSON }} # Optional: Specify if your app requires
                # tokens for building or running tests. Put it into a JSON object where `key` is the name in the
                # env and `value` is the secret
